#!/usr/bin/env sh

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa
yabai -m signal --add event=display_added action="sleep 2 && $HOME/.config/yabai/create_spaces.sh"
yabai -m signal --add event=display_removed action="sleep 1 && $HOME/.config/yabai/create_spaces.sh"
yabai -m signal --add event=window_created action="sketchybar --trigger windows_on_spaces"
yabai -m signal --add event=window_destroyed action="sketchybar --trigger windows_on_spaces"
yabai -m signal --add event=window_focused action="sketchybar --trigger window_focus"

$HOME/.config/yabai/create_spaces.sh

yabai -m config external_bar               all:34:0     \
                window_border              on           \
                mouse_follows_focus        off          \
                focus_follows_mouse        off          \
                window_zoom_persist        off          \
                window_placement           second_child \
                window_topmost             off          \
                window_shadow              float        \
                window_opacity             on           \
                window_opacity_duration    0.15         \
                active_window_opacity      1.0          \
                normal_window_opacity      0.98         \
                window_border_width        2            \
                window_border_hidpi        off          \
                window_border_radius       11           \
                window_animation_duration  0.00         \
                active_window_border_color 0xffe1e3e4   \
                normal_window_border_color 0xff2a2f38   \
                insert_feedback_color      0xff9dd274   \
                split_ratio                0.50         \
                auto_balance               off          \
                mouse_modifier             fn           \
                mouse_action1              move         \
                mouse_action2              resize       \
                mouse_drop_action          swap         \
                                                        \
                top_padding                5            \
                bottom_padding             5            \
                left_padding               10           \
                right_padding              10           \
                window_gap                 8            \
                window_border_blur off

yabai -m config layout bsp

# Exclude problematic apps from being managed:
yabai -m rule --add app="^(Calculator|Software Update|Dictionary|System Settings|System Information|zoom.us|Photo Booth|Archive Utility|Python|App Store|Steam|Activity Monitor|Spotify|Numi|Finder|KiCad|LINE)$" manage=off
# yabai -m rule --add label="Finder" app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off
# yabai -m rule --add label="Safari" app="^Safari$" title="^(General|(Tab|Password|Website|Extension)s|AutoFill|Se(arch|curity)|Privacy|Advance)$" manage=off
yabai -m rule --add label="About This Mac" app="System Information" title="About This Mac" manage=off
# yabai -m rule --add label="Select file to save to" app="^Inkscape$" title="Select file to save to" manage=off
yabai -m rule --add label="Arc browser" app="^Arc$" title="^(Peeranut|General|Max|Shortcuts|Links|Advanced)$" manage=off
yabai -m rule --add label="Arc PiP" app="^Arc$" subrole="^AXSystemDialog$" manage=off

yabai -m space 1 --label note
open "obsidian://open?vault=personal"
open "obsidian://open?vault=know-how"
yabai -m rule --add app="^Obsidian$" space=note

yabai -m space 2 --label office
yabai -m rule --add app="^Slack$" space=office

yabai -m space 3 --label code
yabai -m rule --add app="^WezTerm$" space=code


echo "yabai configuration loaded.."
