#!/usr/bin/env sh

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa
yabai -m signal --add event=display_added action="sleep 2 && $HOME/.config/yabai/create_spaces.sh"
yabai -m signal --add event=display_removed action="sleep 1 && $HOME/.config/yabai/create_spaces.sh"
yabai -m signal --add event=window_created action="sketchybar --trigger windows_on_spaces"
yabai -m signal --add event=window_destroyed action="sketchybar --trigger windows_on_spaces"
yabai -m signal --add event=window_focused action="sketchybar --trigger window_focus"

# INFO: workaround for ghostty terminal
yabai -m signal --add  app='^Ghostty$' event=window_created action='yabai -m space --layout bsp'
yabai -m signal --add  app='^Ghostty$' event=window_destroyed action='yabai -m space --layout bsp'

$HOME/.config/yabai/create_spaces.sh

yabai -m config external_bar               all:0:0      \
                mouse_follows_focus        off          \
                focus_follows_mouse        off          \
                menubar_opacity            1.0          \
                                                        \
                window_zoom_persist        off          \
                window_placement           second_child \
                window_topmost             off          \
                window_shadow              float        \
                window_origin_display      cursor       \
                                                        \
                window_opacity             on           \
                window_opacity_duration    0.15         \
                active_window_opacity      1.0          \
                normal_window_opacity      0.98         \
                window_border_width        2            \
                window_border_hidpi        off          \
                window_border_radius       11           \
                window_animation_duration  0.00         \
                active_window_border_color 0xffe1e3e4   \
                normal_window_border_color 0xff2a2f38   \
                insert_feedback_color      0xff9dd274   \
                split_ratio                0.50         \
                auto_balance               off          \
                mouse_modifier             fn           \
                mouse_action1              move         \
                mouse_action2              resize       \
                mouse_drop_action          swap         \
                                                        \
                top_padding                5            \
                bottom_padding             5            \
                left_padding               10           \
                right_padding              10           \
                window_gap                 8            \
                window_border_blur off

yabai -m config layout bsp

# JankyBorders
borders active_color=0xffe1e3e4 inactive_color=0xff494d64 width=5.0 &

echo "yabai configuration loaded.."
